### ISSUE TITLE
How to use drRead.csv with csv on HDFS?

### ISSUE THREAD

**Issue by jrounds** [tesseradata/datadr#73]
Hi,

I am not quite sure how to use drRead.csv with csv on HDFS.  The help for drRead.csv seems to indicate that it is possible.  I tried the paradigm of hdfsConn and ran into this (follows).  I was intending to use that as an input argument.   Any ideas?

```
> rhput(file.path(getwd(),flu_data_dir, "ili_2000_2013.csv"), "ili_2000_2013_csv")
> rhls("ili_2000_2013_csv")
  permission   owner   group     size          modtime                                   file
1 -rw-r--r-- roun308 roun308 6.282 gb 2015-09-15 11:32 /user/roun308/chiron/ili_2000_2013_csv
> rhchmod("ili_2000_2013_csv", 777)
> in1 = hdfsConn("/user/roun308/chiron/ili_2000_2013_csv", type="text")
* Saving connection attributes
Error in .jcall("RJavaTools", "Ljava/lang/Object;", "invokeMethod", cl,  : 
  org.apache.hadoop.fs.FileAlreadyExistsException: Parent path is not a directory: /user/roun308/chiron/ili_2000_2013_csv ili_2000_2013_csv
	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.mkdirsRecursively(FSNamesystem.java:4146)
	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.mkdirsInternal(FSNamesystem.java:4098)
	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.mkdirsInt(FSNamesystem.java:4057)
	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.mkdirs(FSNamesystem.java:4030)
	at org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.mkdirs(NameNodeRpcServer.java:787)
	at org.apache.hadoop.hdfs.server.namenode.AuthorizationProviderProxyClientProtocol.mkdirs(AuthorizationProviderProxyClientProtocol.java:297)
	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.mkdirs(ClientNamenodeProtocolServerSideTranslatorPB.java:594)
	at org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$ClientNamenodeProtocol$2.cal
```

**Comment by hafen** [comment]
It is expecting a directory with one or more csv files inside it as the input.  Probably would be good to have a check in place to let you know.

**Comment by jrounds** [comment]
It has been an eye-opening experience trying to catch up on the Tessera changes after two years.  I get to see everything from a new users point of view =)  Thanks Ryan.
